/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AJFVCjframes;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import AJFVCclases.AJFVCconexion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author gweng
 */
public class AJFVCreportes extends javax.swing.JFrame {

    String[] meses = {"enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", ""};
    FondoPanel fondo = new FondoPanel();
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form AJFVCreportes
     */
    public AJFVCreportes() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clave = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("VOLVER A LA PÁGINA PRINCIPAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla.setBackground(new java.awt.Color(102, 102, 102));
        tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabla.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabla);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Reporte alumnos que pagaron");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Cuotas pagadas de un alumno");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("cuotas faltantes de un alumno");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setText("Número de cuotas del alumno");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setText("Cuotas faltantes de los alumnos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton7.setText("Cuotas faltantes del alumno");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton8.setText("Saldo de un alumno");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton9.setText("Alumnos sin mora");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton10.setText("Alumnos con mora");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese la clave del alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)
                        .addGap(36, 36, 36)
                        .addComponent(jButton5)
                        .addGap(50, 50, 50)
                        .addComponent(jButton6)
                        .addGap(45, 45, 45)
                        .addComponent(jButton7)
                        .addGap(32, 32, 32)
                        .addComponent(jButton8)
                        .addGap(33, 33, 33)
                        .addComponent(jButton9)
                        .addGap(32, 32, 32)
                        .addComponent(jButton10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Pagos _hechos",};
        String[] Registros = new String[3];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT clave, nombre, cuotas_pagadas FROM alumno; ");
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[0] = rs.getString("clave");
                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("cuotas_pagadas");

                Model.addRow(Registros);
            }
            tabla.setModel(Model);

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Pagos _hechos"};
        String[] Registros = new String[3];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT clave, nombre, cuotas_pagadas FROM alumno where clave =?; ");
            ps.setString(1, clave.getText());
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[0] = rs.getString("clave");
                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("cuotas_pagadas");

                Model.addRow(Registros);
            }
            tabla.setModel(Model);

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Pagos _faltantes",};
        String[] Registros = new String[3];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT clave, nombre, cuotas_pendientes FROM alumno where clave =?; ");
            ps.setString(1, clave.getText());
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[0] = rs.getString("clave");
                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("cuotas_pendientes");

                Model.addRow(Registros);
            }
            tabla.setModel(Model);

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Pagos _hechos"};
        String[] Registros = new String[3];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT nombre, cuotas_pagadas FROM alumno where clave =?; ");
            ps.setString(1, clave.getText());
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("cuotas_pagadas");

            }
            JOptionPane.showMessageDialog(null, "El Alumno  " + " " + Registros[1] + "  " + "ha realizado :  \n" + Registros[2] + "  " + "Cuotas.");

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Pagos _Pendientes",};
        String[] Registros = new String[3];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT clave, nombre, cuotas_pendientes FROM alumno; ");
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[0] = rs.getString("clave");
                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("cuotas_pendientes");

                Model.addRow(Registros);
            }
            tabla.setModel(Model);

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Connection con = null;

        String[] Registros = new String[3];

        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT nombre, cuotas_pendientes FROM alumno where clave =?; ");
            ps.setString(1, clave.getText());
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("cuotas_pendientes");

            }
            JOptionPane.showMessageDialog(null, "El Alumno" + " " + Registros[1] + "  " + " le falta cancelar  :  \n" + Registros[2] + "  " + "Cuotas.");

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Saldo_actual",};
        String[] Registros = new String[3];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT clave, nombre, total FROM alumno where clave =?;");
            ps.setString(1, clave.getText());
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[0] = rs.getString("clave");
                Registros[1] = rs.getString("nombre");
                Registros[2] = "Q" + rs.getString("total");

                Model.addRow(Registros);
            }
            tabla.setModel(Model);

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Mora","Total csin mora"};
        String[] Registros = new String[4];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT clave, nombre, mora, total FROM alumno where mora ='No';");
            
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[0] = rs.getString("clave");
                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("mora");
                Registros[3] = rs.getString("total");

                Model.addRow(Registros);
            }
            tabla.setModel(Model);

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                Connection con = null;
        String[] Titulos = {"Clave", "Nombre", "Mora","Total con mora"};
        String[] Registros = new String[4];
        DefaultTableModel Model = new DefaultTableModel(null, Titulos);
        try {
            con = AJFVCconexion.getConnection();
            ps = con.prepareStatement("SELECT clave, nombre, mora, total FROM alumno where mora ='SI';");
            
            rs = ps.executeQuery();
            while (rs.next()) {

                Registros[0] = rs.getString("clave");
                Registros[1] = rs.getString("nombre");
                Registros[2] = rs.getString("mora");
                Registros[3] = rs.getString("total");

                Model.addRow(Registros);
            }
            tabla.setModel(Model);

            con.close();
        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AJFVCmainwindow main = new AJFVCmainwindow();
        main.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AJFVCreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AJFVCreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AJFVCreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AJFVCreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AJFVCreportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        public Image imagen;

        @Override
        public void paint(Graphics g) {
            try {
                imagen = new ImageIcon(getClass().getResource("/AJFVCimágenesvarias/fondo.jpg")).getImage();
            } catch (NullPointerException e) {

            }
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
